// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.mlag.model;

import org.mlag.model.UserRoles;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserRoles_Roo_Configurable {
    
    declare @type: UserRoles: @Configurable;
    
}
